catalog:
    vite: npm:@voidzero-dev/vite-plus-core@0.3.3
    vite-plus: 0.3.3
minimumReleaseAgeExclude:
    - '@types/node@26.6.2'
overrides:
    vite@*: 'catalog:'
peerDependencyRules:
    allowAny:
        - vite
    allowedVersions:
        vite: '*'
